import Head from 'next/head'
import {Inter } from 'next/font/google'
import Hero from '../../components/Hero'
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'
import { InstagramEmbed } from 'react-social-media-embed';
import React from 'react';
import Gallery from 'react-grid-gallery';

const longImgStyle = { maxWidth: '95%' }

const IMAGES =
  [
            {
      src: "mainPageGallery/beachGirls2.png",
      thumbnail:  "mainPageGallery/beachGirls2.png",
      thumbnailWidth: 450,
      thumbnailHeight: 450,
      caption: "@GoSleepyHead"
    },
    
     {
      src: "mainPageGallery/FairyTailGirls.png",
      thumbnail:  "mainPageGallery/FairyTailGirls.png",
      thumbnailWidth: 750,
      thumbnailHeight: 450,
      caption: "@GoSleepyHead"
    },
         {
      src: "mainPageGallery/jessi pokemon Cropped.png",
      thumbnail:  "mainPageGallery/jessi pokemon Cropped.png",
      thumbnailWidth: 650,
      thumbnailHeight: 450,
      caption: "@GoSleepyHead"
    },
             {
      src: "mainPageGallery/Lillie.png",
      thumbnail:  "mainPageGallery/Lillie.png",
      thumbnailWidth: 470,
      thumbnailHeight: 450,
      caption: "@GoSleepyHead"
    },
          {
        src: "mainPageGallery/shinji xtc.png",
        thumbnail:  "mainPageGallery/shinji xtc.png",
        thumbnailWidth: 350,
        thumbnailHeight: 312,
        caption: "@GoSleepyHead"
      },
    {
      src: "mainPageGallery/TagakiSanlaughBackG.png",
      thumbnail:  "mainPageGallery/TagakiSanlaughBackG.png",
      thumbnailWidth: 200,
      thumbnailHeight: 169,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/TagakiSanWaterBackG.png",
      thumbnail:  "mainPageGallery/TagakiSanWaterBackG.png",
      thumbnailWidth: 200,
      thumbnailHeight: 200,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/ShinjiSittingTrain.png",
      thumbnail:  "mainPageGallery/ShinjiSittingTrain.png",
      thumbnailWidth: 300,
      thumbnailHeight: 180,
      caption: "@GoSleepyHead"
    },
      {
        src: "mainPageGallery/jessietall sad.png",
        thumbnail:  "mainPageGallery/jessietall sad.png",
        thumbnailWidth: 200,
        thumbnailHeight: 200,
        caption: "@GoSleepyHead"
      },
      

      {
        src: "mainPageGallery/shinji blu.png",
        thumbnail:  "mainPageGallery/shinji blu.png",
        thumbnailWidth: 350,
        thumbnailHeight: 312,
        caption: "@GoSleepyHead"
      },
      
    {
      src: "mainPageGallery/rei look up3.png",
      thumbnail:  "mainPageGallery/rei look up3.png",
      thumbnailWidth: 400,
      thumbnailHeight: 412,
      caption: "@GoSleepyHead"
    },

    {
      src: "mainPageGallery/lucy2.png",
      thumbnail:  "mainPageGallery/lucy2.png",
      thumbnailWidth: 320,
      thumbnailHeight: 412,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/rei standasd.png",
      thumbnail:  "mainPageGallery/rei standasd.png",
      thumbnailWidth: 350,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/nami crack.png",
      thumbnail:  "mainPageGallery/nami crack.png",
      thumbnailWidth: 320,
      thumbnailHeight: 312,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/re8 Olga 1.png",
      thumbnail:  "mainPageGallery/re8 Olga 1.png",
      thumbnailWidth: 450,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },

    {
      src: "mainPageGallery/asuka kimono.png",
      thumbnail:  "mainPageGallery/asuka kimono.png",
      thumbnailWidth: 280,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/mallow header.png",
      thumbnail:  "mainPageGallery/mallow header.png",
      thumbnailWidth: 500,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },
    
    {
      src: "mainPageGallery/mallowOutKimonoRedux.png",
      thumbnail:  "mainPageGallery/mallowOutKimonoRedux.png",
      thumbnailWidth: 450,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },
    {
      src: "mainPageGallery/asuka kimono1.png",
      thumbnail:  "mainPageGallery/asuka kimono1.png",
      thumbnailWidth: 580,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },

    {
      src: "mainPageGallery/nami low 4.png",
      thumbnail:  "mainPageGallery/nami low 4.png",
      thumbnailWidth: 499,
      thumbnailHeight: 512,
      caption: "@GoSleepyHead"
    },

    // {
    //   src: "mainPageGallery/rebecca gun.png",
    //   thumbnail:  "mainPageGallery/rebecca gun.png",
    //   thumbnailWidth: 450,
    //   thumbnailHeight: 450,
    //   caption: "@GoSleepyHead"
    // },


  ]

  

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>

      <Head>

        <title>SleepyHead Comics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero heading='SleepyHead Comics' message='The story about a narcoleptic superhero in Stroke City!' />

      <div id='galleryZoom' className='max-w-[1240px] mx-auto'>
        <p className="py-5"></p>

        <div id='gallery' className='max-w-[1240px] py-4 mx-auto'>
          <h1 style={{
            fontSize: '2.8rem',
            lineHeight: '1rem',
            textAlign: 'center',
            color: 'black',
            padding: '2',
            fontFamily: '-moz-initial'
          }}>Gallery</h1>
        </div>

        <hr
          style={{
            background: 'brown',
            color: 'brown',
            borderColor: 'brown',
            width: '70%',
            margin: 'auto'
          }}
        />
        <p className="py-5"></p>
        <div id='gallery' className='max-w-[900px]  mx-auto'>
        <Gallery images={IMAGES} enableImageSelection={false}  />

        </div>


        <div className="py-5"overlayBgColorEnd={'rgba(0, 0, 0, 0.94)'} >
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>
        <h1 > ​​​​</h1>      <h1> ​​​​</h1>
    
        </div>

        


{/* START GRID PART WITH WHITE TULIPS */}
      <div className='center'>
          
          <Zoom overlayBgColorEnd={'rgba(0, 0, 0, 0.94)'} >
          <img alt="landscape" src='/ecchi/mAIKA KAMNIURAI.png' width="400" height="600"
          />
        </Zoom>
    





  

   
    </div>

      </div>
{/* START GRID PART WITH WHITE TULIPS */}



      {/* <Slider slides={SliderData} /> */}
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <InstagramEmbed url="https://www.instagram.com/p/CtKtlOGNdIX/" width={328} />
      </div>


    </div>
  );
}
